/* eslint-disable @typescript-eslint/indent */
export enum NotificationInfo {
    TransactionSuccessful = 'Transaction successful!',
    TransactionSuccessfulDesc = 'Your transaction has been confirmed successfully.',
    LogInSuccessfully = 'Logged in sucessfully!',
    ClaimSuccessfully = 'Claimed sucessfully!',
    ClaimSuccessfullyDesc = 'You hav claimed test USDC.',
    ClaimSuccessfullyFOFDesc = 'You hav claimed $FOF.',
    CreatePoolSuccessful = 'Pools creation successful!',
    CreatePoolSuccessfulDesc = 'You have created your Pools successfully.',
    CreateLoanSuccessfully = 'Loan creation successful!',
    CreateLoanSuccessfullyDesc = 'You have created a Loan successfully.',
    MintSuccessfully = 'Mint successfully!',
    MintSuccessfullyDesc = 'You have mint a follow nft successfully.',
    ApprovalSuccessfully = 'Approval successfully.',
    ApprovalSuccessfullyDesc = 'You have approved successfully.',
    DepositSuccessfully = 'Deposit successful.',
    DepositSuccessfullyDesc = 'You have deposited successfully.',
    FollowSuccessfully = 'Follow successfully.',
    FollowSuccessfullyDesc = 'You have followed successfully.',
    WithdrawSuccessfully = 'Withdraw successfully.',
    WithdrawSuccessfullyDesc = 'You have withdrawn successfully.',
}
