/* eslint-disable @typescript-eslint/indent */
export enum NotificationInfo {
    TransactionSuccessful = 'Transaction successful!',
    TransactionSuccessfulDesc = 'Your transaction has been confirmed successfully.',
    LogInSuccessfully = 'Logged in sucessfully!',
    ClaimSuccessfully = 'Claimed sucessfully!',
    ClaimSuccessfullyDesc = 'You have claimed test USDC.',
    ClaimSuccessfullyFOFDesc = 'You have claimed $FOF.',
    CreatePoolSuccessful = 'Pools creation successful!',
    CreatePoolSuccessfulDesc = 'You have created your Pools successfully.',
    CreateLoanSuccessfully = 'Loan creation successful!',
    CreateLoanSuccessfullyDesc = 'You have created a Loan successfully.',
    MintSuccessfully = 'Mint successfully!',
    MintSuccessfullyDesc = 'You have mint a follow nft successfully.',
    ApprovalSuccessfully = 'Approval successfully!',
    ApprovalSuccessfullyDesc = 'You have approved successfully.',
    DepositSuccessfully = 'Deposit successful!',
    DepositSuccessfullyDesc = 'You have deposited successfully.',
    FollowSuccessfully = 'Follow successfully!',
    FollowSuccessfullyDesc = 'You have followed successfully.',
    WithdrawSuccessfully = 'Withdraw successfully!',
    WithdrawSuccessfullyDesc = 'You have withdrawn successfully.',
    ListSuccessfully = 'List successfully!',
    ListSuccessfullyDesc = 'You have listed successfully.',
    LiquidateSuccessfully = 'Liquidation successfully!',
    LiquidateSuccessfullyDesc = 'You have liquidated successfully.',
    FaucetSuccessfully = 'Claimed successfully!',
    FaucetSuccessfullyDesc = 'You have claimed USDC successfully.',
}
